version: '3.8'

x-app-service: &default-app
  build:
    context: ./Infra/php
    dockerfile: Dockerfile
    target: dev
  command: ''
  volumes:
    - ./Code:/Code:delegated

services:
  shop:
    <<: *default-app
    container_name: cooldevguys-skeleton-shop
    env_file:
      - .env.shop
    ports:
      - "8881:8030"
      - "9030:9001"
    depends_on:
      - shared_rabbitmq
      - shared_mysql

  dashboard:
    <<: *default-app
    container_name: cooldevguys-skeleton-dashboard
    env_file:
      - .env.dashboard
    ports:
      - "8882:8040"
      - "9040:9001"
    depends_on:
      - shared_rabbitmq

  shared_nginx:
    container_name: cooldevguys-skeleton-shared_nginx
    build:
      context: ./Infra/nginx
      dockerfile: Dockerfile
    ports:
      - "8001"
      - "8002"
    depends_on:
      - shop
      - dashboard

  shared_elasticsearch:
    container_name: cooldevguys-skeleton-shared_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  shared_mysql:
    container_name: cooldevguys-skeleton-shared_mysql
    image: mysql:8.0
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  shared_rabbitmq:
    container_name: cooldevguys-skeleton-shared_rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - "5630:5672"
      - "8090:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabb1t
