version: '3.8'

services:
  shop:
    build:
      context: .
      dockerfile: ./Infra/php/Dockerfile
      target: dev
    volumes:
      - ./Code:/Code:rw
    container_name: cooldevguys-skeleton-shop
    env_file:
      - Code/.env.shop
#    depends_on:
#      - shared_rabbitmq
#      - shared_mysql

  dashboard:
    build:
      context: .
      dockerfile: ./Infra/php/Dockerfile
      target: dev
    volumes:
      - ./Code:/Code:rw
    container_name: cooldevguys-skeleton-dashboard
    env_file:
      - Code/.env.dashboard
#    depends_on:
#      - shared_rabbitmq

  shop_nginx:
    container_name: cooldevguys-skeleton-shop_nginx
    build:
      context: ./Infra/nginx
      dockerfile: Dockerfile
      target: shop-dev
    ports:
      - "8001:8001"
    depends_on:
      - shop

  dashboard_nginx:
    container_name: cooldevguys-skeleton-dashboard_nginx
    build:
      context: ./Infra/nginx
      dockerfile: Dockerfile
      target: dashboard-dev
    ports:
      - "8002:8002"
    depends_on:
      - dashboard

#  shared_elasticsearch:
#    container_name: cooldevguys-skeleton-shared_elastic
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  shared_mysql:
    container_name: cooldevguys-skeleton-shared_mysql
    image: mysql:8.0
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  shared_rabbitmq:
    container_name: cooldevguys-skeleton-shared_rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - "5630:5672"
      - "8090:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabb1t
