apiVersion: v1
kind: Service
metadata:
  name: shared-mysql
  namespace: shop
  labels:
    app: shop-db
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30008
  selector:
    app: shop-db
