FROM nginx:1.17.1-alpine

COPY shop.conf /etc/nginx/conf.d/shop.conf
COPY dashboard.conf /etc/nginx/conf.d/dashboard.conf
COPY public /Code/applications/shop/public
COPY public /Code/applications/dashboard/public
