imports:
  - { resource: ../../../../src/Store/Shared/Infrastructure/Symfony/DependencyInjection/store_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  _instanceof:
    CoolDevGuys\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: ['cooldevguys.domain_event_subscriber']

    CoolDevGuys\Shared\Domain\Bus\Command\CommandHandler:
      tags: ['cooldevguys.command_handler']

    CoolDevGuys\Shared\Domain\Bus\Query\QueryHandler:
      tags: ['cooldevguys.query_handler']

  CoolDevGuys\Applications\Store\Entrypoints\Controller\:
    resource: '../entrypoints/Controller'
    tags: ['controller.service_arguments']

  CoolDevGuys\Shared\:
    resource: '../../../../src/Shared'

  CoolDevGuys\Store\:
    resource: '../../../../src/Store'

  CoolDevGuys\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [!tagged cooldevguys.domain_event_subscriber]
    lazy: true

  CoolDevGuys\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [!tagged cooldevguys.domain_event_subscriber]

  CoolDevGuys\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
    arguments: [!tagged cooldevguys.domain_event_subscriber]

  CoolDevGuys\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [!tagged cooldevguys.database_connection]

  CoolDevGuys\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  CoolDevGuys\Shared\Infrastructure\Symfony\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException }

  CoolDevGuys\Shared\Infrastructure\Symfony\BasicHttpAuthMiddleware:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  CoolDevGuys\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    arguments: [!tagged cooldevguys.command_handler]

  CoolDevGuys\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    arguments: [!tagged cooldevguys.query_handler]

  CoolDevGuys\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection:
    arguments:
      - host: '%env(RABBITMQ_HOST)%'
        port: '%env(RABBITMQ_PORT)%'
        vhost: '%env(RABBITMQ_STORE_VHOST)%'
        login: '%env(RABBITMQ_LOGIN)%'
        password: '%env(RABBITMQ_PASSWORD)%'
        read_timeout: 2
        write_timeout: 2
        connect_timeout: 5

  CoolDevGuys\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus:
    arguments: ['@CoolDevGuys\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection', '%env(RABBITMQ_EXCHANGE)%']

  CoolDevGuys\Shared\Domain\Bus\Event\EventBus: '@CoolDevGuys\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus'
