imports:
  - { resource: ../../../src/Shop/Shared/Infrastructure/Symfony/DependencyInjection/shop_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  _instanceof:
    CoolDevGuys\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'cooldevguys.domain_event_subscriber' ]

    CoolDevGuys\Shared\Domain\Bus\Command\CommandHandler:
      tags: [ 'cooldevguys.command_handler' ]

    CoolDevGuys\Shared\Domain\Bus\Query\QueryHandler:
      tags: [ 'cooldevguys.query_handler' ]

  CoolDevGuys\Applications\Shop\Controller\:
    resource: '../entrypoints/Controller'
    tags: ['controller.service_arguments']

  CoolDevGuys\Shared\:
    resource: '../../../src/Shared'

  CoolDevGuys\Shop\:
    resource: '../../../src/Shop'

  # -- Tagging --
  CoolDevGuys\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged cooldevguys.domain_event_subscriber ]
    lazy: true

  CoolDevGuys\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [ !tagged cooldevguys.domain_event_subscriber ]

  CoolDevGuys\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
    arguments: [ !tagged cooldevguys.domain_event_subscriber ]

  CoolDevGuys\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [ !tagged cooldevguys.database_connection ]

  CoolDevGuys\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    arguments: [ !tagged cooldevguys.command_handler ]

  CoolDevGuys\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    arguments: [ !tagged cooldevguys.query_handler ]

  # -- Listeners --
  CoolDevGuys\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  CoolDevGuys\Shared\Infrastructure\Symfony\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException }

  CoolDevGuys\Shared\Infrastructure\Symfony\ParseJsonApiResponseListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  CoolDevGuys\Shared\Infrastructure\Symfony\ApiRequestValidatorListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  CoolDevGuys\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection:
    arguments:
      - host: '%env(RABBITMQ_HOST)%'
        port: '%env(RABBITMQ_PORT)%'
        vhost: '%env(RABBITMQ_STORE_VHOST)%'
        login: '%env(RABBITMQ_LOGIN)%'
        password: '%env(RABBITMQ_PASSWORD)%'
        read_timeout: 2
        write_timeout: 2
        connect_timeout: 5

  CoolDevGuys\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus:
    arguments: ['@CoolDevGuys\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection', '%env(RABBITMQ_EXCHANGE)%']

  CoolDevGuys\Shared\Domain\Bus\Event\EventBus: '@CoolDevGuys\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus'
