apiVersion: v1
kind: Secret
metadata:
  labels:
    app: shop
  name: shop
  namespace: shop
type: Opaque
data:
  secret_token_staging: ZjZmMjRmMzU3MTE2YTQ5NzRiOWI0NmRkNjRkNDA5YjQ=
  secret_token_prod: ZjZmMjRmMzU3MTE2YTQ5NzRiOWI0NmRkNjRkNDA5YjQ=
  client_password_staging: YXBpUGFzc3dvcmQ=
  client_password_prod: YXBpUGFzc3dvcmQ=
  jwt_secret_key_staging: Cg==
  jwt_secret_key_prod: Cg==
  jwt_public_key_staging: Cg==
  jwt_public_key_prod: Cg==
  jwt_phassphrase_staging: Cg==
  jwt_phassphrase_prod: Cg==
  database_user_staging: cm9vdA==
  database_user_prod: cm9vdA==
  database_password_staging: c3VwM3Iuc2VDcjN0X3BhcyR3MHJk
  database_password_prod: c3VwM3Iuc2VDcjN0X3BhcyR3MHJk
  sentry_dsn_staging: aHR0cHM6Ly9iODA2OGMyZGJmMDY0NmFlYTI1ODBiN2E4MGFjMTM4NUBvMTExODI1NS5pbmdlc3Quc2VudHJ5LmlvLzYxNTIwNTM=
  sentry_dsn_prod: aHR0cHM6Ly9iODA2OGMyZGJmMDY0NmFlYTI1ODBiN2E4MGFjMTM4NUBvMTExODI1NS5pbmdlc3Quc2VudHJ5LmlvLzYxNTIwNTM=
