services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [ CoolDevGuys\Shop\Shared\Infrastructure\Doctrine\ShopEntityManagerFactory, create ]
    arguments:
      - driver: '%env(SHOP_DATABASE_DRIVER)%'
        host: '%env(SHOP_DATABASE_HOST)%'
        port: '%env(SHOP_DATABASE_PORT)%'
        dbname: '%env(SHOP_DATABASE_NAME)%'
        user: '%env(SHOP_DATABASE_USER)%'
        password: '%env(SHOP_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: cooldevguys.database_connection }
    public: true


  # Products
  CoolDevGuys\Shop\Products\Domain\ProductRepository: '@CoolDevGuys\Shop\Products\Infrastructure\Persistence\DoctrineProductRepository'
