#!/bin/sh
set -e

# Set default value to false if the environment variable is not set
ENABLE_XDEBUG=${ENABLE_XDEBUG:-"false"}
DOCKER_PHP_XDEBUG_EXTENSION=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# If the environment variable ENABLE_XDEBUG=true and the docker-php-ext-xdebug.ini
# symlink does not exists yet, enable xdebug via symlink.
if [ "$ENABLE_XDEBUG" = "true" ] && [ ! -L "$DOCKER_PHP_XDEBUG_EXTENSION" ]; then
  ln -s /usr/local/etc/php/docker-php-ext-xdebug.ini "$DOCKER_PHP_XDEBUG_EXTENSION"
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"
